name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      
      - name: Install Dependencies
        run: |
          cd client && npm install
      
      - name: Fix Permissions for react-scripts
        run: |
          chmod +x ./client/node_modules/.bin/react-scripts
      
      - name: Run Tests
        run: |
          cd client && npm test
      
      - name: Build Application
        run: |
          cd client && npm run build
      
      - name: Deploy to EC2
        env:
          PRIVATE_KEY: ${{ secrets.EC2_PRIVATE_KEY }}
          HOST: ${{ secrets.EC2_HOST }}
          USERNAME: ${{ secrets.EC2_USERNAME }}
        run: |
          echo "$PRIVATE_KEY" > private_key.pem
          chmod 600 private_key.pem
          scp -o StrictHostKeyChecking=no -i private_key.pem -r client/build/* $USERNAME@$HOST:/var/www/html/
